# Generated by Django 3.1.5 on 2021-05-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=45)),
                ('agent_type', models.CharField(max_length=45)),
                ('manufacturer', models.CharField(max_length=45)),
                ('firstoperationdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('emergencylevel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=45)),
                ('cost', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('datecreated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_sensor', to='Home.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=45)),
                ('priority', models.IntegerField()),
                ('describtion', models.CharField(max_length=150)),
                ('session', models.ManyToManyField(blank=True, related_name='task_session', to='Home.session')),
            ],
        ),
        migrations.CreateModel(
            name='snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.BinaryField()),
                ('datetaken', models.IntegerField()),
                ('time', models.CharField(max_length=150)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_agent', to='Home.agent')),
                ('session', models.ManyToManyField(blank=True, related_name='snapshot_session', to='Home.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_user', to='Home.user'),
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datereported', models.IntegerField()),
                ('time', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_agent', to='Home.agent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='Home.event')),
            ],
        ),
        migrations.CreateModel(
            name='measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.IntegerField()),
                ('value', models.IntegerField()),
                ('date', models.IntegerField()),
                ('time', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_agent', to='Home.agent')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_sensor', to='Home.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='agenttask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateassigned', models.IntegerField()),
                ('timeassigned', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('dateaccomplished', models.IntegerField()),
                ('timeaccomplished', models.IntegerField()),
                ('comment', models.CharField(max_length=150)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenttask_agent', to='Home.agent')),
                ('session', models.ManyToManyField(blank=True, related_name='agenttask_session', to='Home.session')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenttask_task', to='Home.task')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='session',
            field=models.ManyToManyField(blank=True, related_name='agent_session', to='Home.session'),
        ),
    ]
