# Generated by Django 3.1.5 on 2021-05-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_measurement_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='date',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
