# Generated by Django 3.1.5 on 2021-05-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210531_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='event_name', max_length=45),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
