# Generated by Django 3.1.5 on 2021-05-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210601_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='datereported',
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
