# Generated by Django 3.1.5 on 2021-05-31 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210601_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_event', to='Home.event'),
        ),
    ]
