# Generated by Django 3.1.5 on 2021-05-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20210601_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttask',
            name='dateaccomplished',
        ),
        migrations.RemoveField(
            model_name='agenttask',
            name='dateassigned',
        ),
        migrations.RemoveField(
            model_name='agenttask',
            name='state',
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='timeaccomplished',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='timeassigned',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
