# Generated by Django 3.1.5 on 2021-05-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20210601_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='timeaccomplished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
