# Generated by Django 3.1.5 on 2021-06-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20210601_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='datetaken',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='title',
            field=models.CharField(default='0000', max_length=45),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='image',
            field=models.ImageField(upload_to='snapshot_image'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
