# Generated by Django 3.1.5 on 2021-07-02 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20210625_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
