# Generated by Django 3.1.5 on 2021-07-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20210702_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='max_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='min_value',
            field=models.FloatField(),
        ),
    ]
