# Generated by Django 3.1.5 on 2021-07-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warning_sensor', to='Home.sensor'),
        ),
        migrations.AddField(
            model_name='warning',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='snapshot',
        ),
    ]
