# Generated by Django 3.1.5 on 2021-07-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20210706_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_agent', to='Home.agent')),
            ],
        ),
    ]
